# Generated by Django 4.1.7 on 2023-03-15 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_alter_studentprofile_id_alter_studentprofile_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='name',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
