# Generated by Django 4.1.7 on 2023-05-31 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_studentprofile_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentfile',
            name='feedback',
            field=models.TextField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='documentfile',
            name='feedback_by',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
