# Generated by Django 4.1.7 on 2023-05-24 07:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_rename_image_university_logo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='university',
            old_name='logo',
            new_name='image',
        ),
    ]
