# Generated by Django 4.1.7 on 2023-05-24 07:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_rename_logo_university_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='university',
            old_name='image',
            new_name='logo',
        ),
    ]
